spring.application.name=application

server.port=5050

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Dang12c6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

paypal.client-id=AcZ7PtrNOxQyRGwA8dgbPWenL2rQMN0NwOee2fcNnA9ycfCLkvFneLT1rmjh0b1Y64KT50K9UYL3t4xq
paypal.client-secret=EFCy52jG69350eKuYclnk4c1HPnw6HqNj0v6iOwsGau_4BivK0XvC6N7yWc-TLaUsBerze08LRbm4X_B
paypal.base-url=https://api-m.sandbox.paypal.com