spring.application.name=application

server.port=5050

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Dang12c6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

spring.app.jwtSecret=cba34b9a3d7d41706d5a676348451f9e8feb67b012bbf9c49195c14412a9c9ac
spring.app.jwtExpirationInMs=360000000